MvcApiClientOAuth/MvcApiClientOAuth/Models/Empleado.cs
namespace MvcApiClientOAuth.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvcApiClientOAuth/MvcApiClientOAuth/Models/ErrorViewModel.cs
namespace MvcApiClientOAuth.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiClientOAuth/MvcApiClientOAuth/Models/LoginModel.cs
namespace MvcApiClientOAuth.Models
{
    public class LoginModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

MvcApiClientOAuth/MvcApiClientOAuth/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcApiClientOAuth.Filters;
using MvcApiClientOAuth.Models;
using MvcApiClientOAuth.Services;
using System.Security.Claims;

namespace MvcApiClientOAuth.Controllers
{

    public class EmpleadosController : Controller
    {
        private ServiceApiEmpleados service;

        public EmpleadosController(ServiceApiEmpleados service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Empleado> empleados =
                await this.service.GetEmpleadosAsync();
            return View(empleados);
        }

        public async Task<IActionResult> Details(int id)
        {
            Empleado empleado =
                await this.service.FindEmpleadoAsync(id);
            return View(empleado);
        }

        [AuthorizeEmpleados]
        public async Task<IActionResult> Perfil()
        {
            Empleado empleado =
                await this.service.GetPerfilEmpleadoAsync();
            return View(empleado);
        }

        [AuthorizeEmpleados]
        public async Task<IActionResult> Compis()
        {
            List<Empleado> empleados =
                await this.service.GetCompisTrabajoAsync();
            return View(empleados);
        }

        public async Task<IActionResult> EmpleadosOficios()
        {
            List<string> oficios =
                await this.service.GetOficiosAsync();
            ViewData["OFICIOS"] = oficios;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult>
            EmpleadosOficios(int? incremento
            , List<string> oficio, string accion)
        {
            List<string> oficios =
                await this.service.GetOficiosAsync();
            ViewData["OFICIOS"] = oficios;
            if (accion.ToLower() == "update")
            {
                await this.service
                    .UpdateEmpleadosOficiosAsync
                    (incremento.Value, oficio);
            }
            List<Empleado> empleados =
                await this.service.GetEmpleadosOficiosAsync
                (oficio);
            return View(empleados);
        }
    }
}

MvcApiClientOAuth/MvcApiClientOAuth/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiClientOAuth.Models;
using System.Diagnostics;

namespace MvcApiClientOAuth.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiClientOAuth/MvcApiClientOAuth/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MvcApiClientOAuth.Models;
using MvcApiClientOAuth.Services;
using System.Security.Claims;

namespace MvcApiClientOAuth.Controllers
{
    public class ManagedController : Controller
    {
        private ServiceApiEmpleados service;

        public ManagedController(ServiceApiEmpleados service)
        {
            this.service = service;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            string token = await this.service
                .GetTokenAsync(model.UserName, model.Password);
            if (token == null)
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
            else
            {
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity =
                    new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme,
                    ClaimTypes.Name, ClaimTypes.Role);
                // Almacenamos el nombre de usuario (bonito)
                identity.AddClaim(new Claim(ClaimTypes.Name, model.UserName));
                // Almacenamos el ID del usuario
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, model.Password));

                identity.AddClaim(new Claim("TOKEN", token));

                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);
                // Damos de alta al usuario indicando que estará
                // validado durante 30 minutos
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal, new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
                    });
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcApiClientOAuth/MvcApiClientOAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiClientOAuth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApiClientOAuth.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiClientOAuth</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black"
                               asp-controller="Empleados"
                               asp-action="EmpleadosOficios">
                                EmpleadosOficios
                            </a>
                        </li>
                        <partial name="_MenuEmpleado" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcApiClientOAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcApiClientOAuth/MvcApiClientOAuth/Views/Shared/_MenuEmpleado.cshtml
@if (Context.User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-black"
           asp-controller="Empleados"
           asp-action="Perfil">
            Perfil
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-black"
           asp-controller="Empleados"
           asp-action="Compis">
            Compañeros
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-danger"
           asp-controller="Managed"
           asp-action="Logout">
            Logout <span class="text-primary">@Context.User.Identity.Name</span>
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-black"
           asp-controller="Empleados"
           asp-action="Index">
            Empleados
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-black"
           asp-controller="Empleados"
           asp-action="Perfil">
            Login
        </a>
    </li>
}