MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Models/Departamento.cs
namespace MvcClienteApiCrudDepartamentos.Models
{
    public class Departamento
    {
        public int DeptNo { get; set; }
        public string Nombre { get; set; }
        public string Localidad { get; set; }
    }
}

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Models/ErrorViewModel.cs
namespace MvcClienteApiCrudDepartamentos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcClienteApiCrudDepartamentos.Models;
using MvcClienteApiCrudDepartamentos.Services;

namespace MvcClienteApiCrudDepartamentos.Controllers
{
    public class DepartamentosController : Controller
    {
        private ServiceApiDepartamentos service;

        public DepartamentosController
            (ServiceApiDepartamentos service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Departamento> departamentos =
                await this.service.GetDepartamentosAsync();
            return View(departamentos);
        }

        public async Task<IActionResult> Details(int id)
        {
            Departamento departamento =
                await this.service.FindDepartamentoAsync(id);
            return View(departamento);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.service.DeleteDepartamentoAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Departamento dept)
        {
            await this.service.InsertDepartamentoAsync
                (dept.DeptNo, dept.Nombre, dept.Localidad);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            Departamento departamento =
                await this.service.FindDepartamentoAsync(id);
            return View(departamento);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Departamento dept)
        {
            await this.service.UpdateDepartamentoAsync
                (dept.DeptNo, dept.Nombre, dept.Localidad);
            return RedirectToAction("Index");
        }

        public IActionResult Cliente()
        {
            return View();
        }
    }
}

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcClienteApiCrudDepartamentos.Models;
using System.Diagnostics;

namespace MvcClienteApiCrudDepartamentos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Views/Departamentos/Cliente.cshtml
@section Scripts {
    <script src="~/js/serviceapidepartamentos.js"></script>
    <script>

        $(function () {
            loadDepartamentos();
            $("#botoninsert").on("click", function () {
                let id = parseInt($("#cajaid").val());
                let nombre = $("#cajanombre").val();
                let localidad = $("#cajalocalidad").val();
                insertDepartamentoAsync(id, nombre, localidad, function () {
                    loadDepartamentos();
                });
            });

            $("#botonupdate").on("click", function () {
                let id = parseInt($("#cajaid").val());
                let nombre = $("#cajanombre").val();
                let localidad = $("#cajalocalidad").val();
                updateDepartamentoAsync(id, nombre, localidad, function () {
                    loadDepartamentos();
                });
            });

            $("#botondelete").on("click", function () {
                let id = $("#cajaid").val();
                deleteDepartamentoAsync(id, function () {
                    loadDepartamentos();
                });
            });
        });



        function loadDepartamentos() {
            getJsonDepartamentosAsync(function (data) {
                let html = "";
                $.each(data, function (index, dept) {
                    html += "<tr>";
                    html += "<td>" + dept.deptNo + "</td>";
                    html += "<td>" + dept.nombre + "</td>";
                    html += "<td>" + dept.localidad + "</td>";
                    html += "</tr>";
                });
                $("#tabladepartamentos tbody").html(html);
            });
        }
    </script>
}

<h1 class="text-primary">
    API CRUD Departamentos
</h1>

<label class="form-label mt-3">ID Departamento</label>
<input type="text" id="cajaid" class="form-control" />
<label class="form-label mt-3">Nombre</label>
<input type="text" id="cajanombre" class="form-control" />
<label class="form-label mt-3">Localidad</label>
<input type="text" id="cajalocalidad" class="form-control" />

<button class="btn btn-dark mt-3" id="botoninsert">
    Insertar
</button>
<button class="btn btn-info mt-3" id="botonupdate">
    Update
</button>
<button class="btn btn-danger mt-3" id="botondelete">
    Delete
</button>

<hr />

<table class="table-borderless mt-3 table" id="tabladepartamentos">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Localidad</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Views/Departamentos/Create.cshtml
@model MvcClienteApiCrudDepartamentos.Models.Departamento

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DeptNo" class="control-label"></label>
                <input asp-for="DeptNo" class="form-control" />
                <span asp-validation-for="DeptNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidad" class="control-label"></label>
                <input asp-for="Localidad" class="form-control" />
                <span asp-validation-for="Localidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Views/Departamentos/Details.cshtml
@model MvcClienteApiCrudDepartamentos.Models.Departamento

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DeptNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DeptNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Localidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Localidad)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DeptNo }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Views/Departamentos/Edit.cshtml
@model MvcClienteApiCrudDepartamentos.Models.Departamento

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DeptNo" class="control-label"></label>
                <input asp-for="DeptNo" class="form-control" />
                <span asp-validation-for="DeptNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidad" class="control-label"></label>
                <input asp-for="Localidad" class="form-control" />
                <span asp-validation-for="Localidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcClienteApiCrudDepartamentos/MvcClienteApiCrudDepartamentos/Views/Departamentos/Index.cshtml
@model IEnumerable<MvcClienteApiCrudDepartamentos.Models.Departamento>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-primary">
    API CRUD Departamentos Server
</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeptNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Localidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DeptNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Localidad)
                </td>
                <td>
                    <a asp-controller="Departamentos"
                       asp-action="Details"
                       asp-route-id="@item.DeptNo"
                       class="btn btn-primary">
                        Details
                    </a>
                    <a asp-controller="Departamentos"
                       asp-action="Edit"
                       asp-route-id="@item.DeptNo"
                       class="btn btn-warning">
                        Edit
                    </a>
                    <a asp-controller="Departamentos"
                       asp-action="Delete" asp-route-id="@item.DeptNo"
                       class="btn btn-danger">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>