MvcCosmosAzure/MvcCosmosAzure/Models/ErrorViewModel.cs
namespace MvcCosmosAzure.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCosmosAzure/MvcCosmosAzure/Models/Motor.cs
namespace MvcCosmosAzure.Models
{
    public class Motor
    {
        public string Tipo { get; set; }
        public int Caballos { get; set; }
        public int Cilindrada { get; set; }
        public bool Turbo { get; set; }
    }
}

MvcCosmosAzure/MvcCosmosAzure/Models/Vehiculo.cs
using Newtonsoft.Json;

namespace MvcCosmosAzure.Models
{
    public class Vehiculo
    {
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
        // Nuestra clase Motor que será la clase dinámica
        public Motor Motor { get; set; }
    }
}

MvcCosmosAzure/MvcCosmosAzure/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCosmosAzure.Models;
using MvcCosmosAzure.Services;

namespace MvcCosmosAzure.Controllers
{
    public class CochesController : Controller
    {
        private ServiceCosmosDb service;

        public CochesController(ServiceCosmosDb service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string accion)
        {
            await this.service.CreateDatabaseAsync();
            ViewData["MENSAJE"] = "Recursos creados en Azure Cosmos";
            return View();
        }

        public async Task<IActionResult> Vehiculos()
        {
            List<Vehiculo> cars =
                await this.service.GetVehiculosAsync();
            return View(cars);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Vehiculo car, string existemotor)
        {
            if (existemotor == null)
            {
                car.Motor = null;
            }
            await this.service.InsertVehiculoAsync(car);
            return RedirectToAction("Vehiculos");
        }

        public async Task<IActionResult> Details(string id)
        {
            Vehiculo car = await this.service.FindVehiculoAsync(id);
            return View(car);
        }

        public async Task<IActionResult> Delete(string id)
        {
            await this.service.DeleteVehiculoAsync(id);
            return RedirectToAction("Vehiculos");
        }

        public async Task<IActionResult> Edit(string id)
        {
            Vehiculo car = await this.service.FindVehiculoAsync(id);
            return View(car);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Vehiculo car)
        {
            await this.service.UpdateVehiculoAsync(car);
            return RedirectToAction("Vehiculos");
        }

        public IActionResult Buscador()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Buscador(string marca)
        {
            List<Vehiculo> cars =
                await this.service.GetVehiculosMarcaAsync(marca);
            return View(cars);
        }
    }
}

MvcCosmosAzure/MvcCosmosAzure/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCosmosAzure.Models;
using System.Diagnostics;

namespace MvcCosmosAzure.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCosmosAzure/MvcCosmosAzure/Views/Coches/Buscador.cshtml
@model IEnumerable<MvcCosmosAzure.Models.Vehiculo>

@{
    ViewData["Title"] = "Vehiculos";
}

<h1>Buscador Vehículos</h1>

<form method="post">
    <label class="form-label">Marca</label>
    <input type="text" name="marca" class="form-control" />
    <button class="btn btn-info">
        Buscar coches
    </button>
</form>
@if (Model != null)
{
    <table class="table-borderless table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Coche</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Marca @item.Modelo</td>
                    <td>
                        <img width="250" height="150" src="@item.Imagen" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCosmosAzure/MvcCosmosAzure/Views/Coches/Create.cshtml
@model MvcCosmosAzure.Models.Vehiculo

@{
    ViewData["Title"] = "Create";
}

@section Scripts {
    <script>
        $(function () {
            $("#existemotor").click(function () {
                $("#capamotor").toggle();
            });
        });
    </script>
}

<h1>Create</h1>

<h4>Vehiculo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <input type="checkbox" id="existemotor"
                   name="existemotor" value="true" /> Vehículo con motor
            <div id="capamotor" style="display:none; float:left;">
                <label class="form-label">Tipo</label>
                <input type="text" name="Motor.Tipo" class="form-control" />
                <label class="form-label">Caballos</label>
                <input type="number" name="Motor.Caballos" class="form-control" />
                <label class="form-label">Cilindrada</label>
                <input type="number" name="Motor.Cilindrada" class="form-control" />
                <label class="form-label">
                    Turbo: <input type="checkbox" name="Motor.Turbo" value="true" />
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Vehiculos">Back to List</a>
</div>

MvcCosmosAzure/MvcCosmosAzure/Views/Coches/Details.cshtml
@model MvcCosmosAzure.Models.Vehiculo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Vehiculo ID @Model.Id</h4>
    <hr />
    <div class="card">
        <img class="card-img-top" src="@Model.Imagen" />
        <div class="card-body">
            <h5 class="card-title">@Model.Marca @Model.Modelo</h5>
            @if (Model.Motor != null)
            {
                <h5 class="card-subtitle">Motor</h5>
                <p class="card-text">Tipo: @Model.Motor.Tipo</p>
                <p class="card-text">Caballos: @Model.Motor.Caballos</p>
                <p class="card-text">Cilindrada: @Model.Motor.Cilindrada</p>
                <p class="card-text">Turbo: @Model.Motor.Turbo</p>


            }
        </div>
    </div>
</div>
<div>
    <a asp-action="Vehiculos">Back to List</a>
</div>

MvcCosmosAzure/MvcCosmosAzure/Views/Coches/Edit.cshtml
@model MvcCosmosAzure.Models.Vehiculo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Vehiculo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Vehiculos">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcCosmosAzure/MvcCosmosAzure/Views/Coches/Index.cshtml
<h1 class="text-primary">
    Azure Cosmos DB
</h1>

<form method="post">
    <button class="btn btn-danger" name="action"
            value="start">
        Generar recursos Cosmos DB
    </button>
</form>

<h2 class="text-danger">
    @ViewData["MENSAJE"]
</h2>

MvcCosmosAzure/MvcCosmosAzure/Views/Coches/Vehiculos.cshtml
@model IEnumerable<MvcCosmosAzure.Models.Vehiculo>

@{
    ViewData["Title"] = "Vehiculos";
}

<h1>Vehiculos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="Buscador">Buscador Coches</a>
</p>
@if (Model != null)
{
    <table class="table-borderless table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Coche</th>
                <th>Imagen</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Marca @item.Modelo</td>
                    <td>
                        <img width="250" height="150" src="@item.Imagen" />
                    </td>
                    <td>
                        <a asp-controller="Coches"
                           asp-action="Details"
                           asp-route-id="@item.Id"
                           class="btn btn-primary btn-sm">
                            Details
                        </a>
                        <a asp-controller="Coches"
                           asp-action="Edit"
                           asp-route-id="@item.Id"
                           class="btn btn-warning btn-sm">
                            Edit
                        </a>
                        <a asp-controller="Coches"
                           asp-action="Delete"
                           asp-route-id="@item.Id"
                           class="btn btn-danger btn-sm">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}